// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package dbgen

import (
	"context"
)

const callUserConfigUpdate = `-- name: CallUserConfigUpdate :exec
CALL pUserConfigUpdate(?, ?, ?, ?)
`

type CallUserConfigUpdateParams struct {
	User       interface{} `json:"user"`
	Namespace  interface{} `json:"namespace"`
	OptionName interface{} `json:"option_name"`
	Value      interface{} `json:"value"`
}

func (q *Queries) CallUserConfigUpdate(ctx context.Context, arg CallUserConfigUpdateParams) error {
	_, err := q.db.ExecContext(ctx, callUserConfigUpdate,
		arg.User,
		arg.Namespace,
		arg.OptionName,
		arg.Value,
	)
	return err
}

const getConfigValues = `-- name: GetConfigValues :many
SELECT user, cnamespace, coption, cvalue FROM tUserConfig WHERE user = ?
`

func (q *Queries) GetConfigValues(ctx context.Context, user string) ([]Tuserconfig, error) {
	rows, err := q.db.QueryContext(ctx, getConfigValues, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tuserconfig
	for rows.Next() {
		var i Tuserconfig
		if err := rows.Scan(
			&i.User,
			&i.Cnamespace,
			&i.Coption,
			&i.Cvalue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
