// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eligibility.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getPendingEligibilityJobs = `-- name: GetPendingEligibilityJobs :many
SELECT id, user, inserted, processed, plugin, payload, response, resubmission, completed FROM tEligibilityJobs WHERE completed = FALSE LIMIT 50
`

func (q *Queries) GetPendingEligibilityJobs(ctx context.Context) ([]Teligibilityjob, error) {
	rows, err := q.db.QueryContext(ctx, getPendingEligibilityJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Teligibilityjob
	for rows.Next() {
		var i Teligibilityjob
		if err := rows.Scan(
			&i.ID,
			&i.User,
			&i.Inserted,
			&i.Processed,
			&i.Plugin,
			&i.Payload,
			&i.Response,
			&i.Resubmission,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEligibilityJob = `-- name: InsertEligibilityJob :execresult
INSERT INTO tEligibilityJobs (user, inserted, plugin, payload)
VALUES (?, ?, ?, ?)
`

type InsertEligibilityJobParams struct {
	User     string         `json:"user"`
	Inserted time.Time      `json:"inserted"`
	Plugin   string         `json:"plugin"`
	Payload  sql.NullString `json:"payload"`
}

func (q *Queries) InsertEligibilityJob(ctx context.Context, arg InsertEligibilityJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertEligibilityJob,
		arg.User,
		arg.Inserted,
		arg.Plugin,
		arg.Payload,
	)
}

const updateEligibilityJobComplete = `-- name: UpdateEligibilityJobComplete :exec
UPDATE tEligibilityJobs
SET completed = TRUE, processed = ?, response = ?
WHERE id = ?
`

type UpdateEligibilityJobCompleteParams struct {
	Processed sql.NullTime   `json:"processed"`
	Response  sql.NullString `json:"response"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateEligibilityJobComplete(ctx context.Context, arg UpdateEligibilityJobCompleteParams) error {
	_, err := q.db.ExecContext(ctx, updateEligibilityJobComplete, arg.Processed, arg.Response, arg.ID)
	return err
}

const updateEligibilityJobFailed = `-- name: UpdateEligibilityJobFailed :exec
UPDATE tEligibilityJobs
SET completed = TRUE, response = ?
WHERE id = ?
`

type UpdateEligibilityJobFailedParams struct {
	Response sql.NullString `json:"response"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateEligibilityJobFailed(ctx context.Context, arg UpdateEligibilityJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateEligibilityJobFailed, arg.Response, arg.ID)
	return err
}
