// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filestore.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getFile = `-- name: GetFile :one
SELECT id, user, stamp, category, filename, payloadid, processorid, content, contentsize FROM tFileStore WHERE user = ? AND category = ? AND filename = ?
`

type GetFileParams struct {
	User     string `json:"user"`
	Category string `json:"category"`
	Filename string `json:"filename"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (Tfilestore, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.User, arg.Category, arg.Filename)
	var i Tfilestore
	err := row.Scan(
		&i.ID,
		&i.User,
		&i.Stamp,
		&i.Category,
		&i.Filename,
		&i.Payloadid,
		&i.Processorid,
		&i.Content,
		&i.Contentsize,
	)
	return i, err
}

const getFileListByMonth = `-- name: GetFileListByMonth :many
SELECT f.filename, f.contentsize AS filesize, p.originalId, p.insert_stamp AS inserted
FROM tFileStore f
LEFT OUTER JOIN tPayload p ON p.id = f.payloadId
WHERE f.user = ? AND f.category = ?
AND DATE_FORMAT(f.stamp, '%Y-%m') = ?
`

type GetFileListByMonthParams struct {
	User     string    `json:"user"`
	Category string    `json:"category"`
	Month    time.Time `json:"month"`
}

type GetFileListByMonthRow struct {
	Filename   string         `json:"filename"`
	Filesize   int64          `json:"filesize"`
	Originalid sql.NullString `json:"originalid"`
	Inserted   sql.NullTime   `json:"inserted"`
}

func (q *Queries) GetFileListByMonth(ctx context.Context, arg GetFileListByMonthParams) ([]GetFileListByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getFileListByMonth, arg.User, arg.Category, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFileListByMonthRow
	for rows.Next() {
		var i GetFileListByMonthRow
		if err := rows.Scan(
			&i.Filename,
			&i.Filesize,
			&i.Originalid,
			&i.Inserted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileListByPayload = `-- name: GetFileListByPayload :many
SELECT f.filename, f.contentsize AS filesize, p.originalId, p.insert_stamp AS inserted
FROM tFileStore f
LEFT OUTER JOIN tPayload p ON p.id = f.payloadId
WHERE f.user = ? AND f.category = ?
AND f.payloadId = ?
`

type GetFileListByPayloadParams struct {
	User      string `json:"user"`
	Category  string `json:"category"`
	PayloadID uint64 `json:"payload_id"`
}

type GetFileListByPayloadRow struct {
	Filename   string         `json:"filename"`
	Filesize   int64          `json:"filesize"`
	Originalid sql.NullString `json:"originalid"`
	Inserted   sql.NullTime   `json:"inserted"`
}

func (q *Queries) GetFileListByPayload(ctx context.Context, arg GetFileListByPayloadParams) ([]GetFileListByPayloadRow, error) {
	rows, err := q.db.QueryContext(ctx, getFileListByPayload, arg.User, arg.Category, arg.PayloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFileListByPayloadRow
	for rows.Next() {
		var i GetFileListByPayloadRow
		if err := rows.Scan(
			&i.Filename,
			&i.Filesize,
			&i.Originalid,
			&i.Inserted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileListByYear = `-- name: GetFileListByYear :many
SELECT f.filename, f.contentsize AS filesize, p.originalId, p.insert_stamp AS inserted
FROM tFileStore f
LEFT OUTER JOIN tPayload p ON p.id = f.payloadId
WHERE f.user = ? AND f.category = ?
AND DATE_FORMAT(f.stamp, '%Y') = ?
`

type GetFileListByYearParams struct {
	User     string    `json:"user"`
	Category string    `json:"category"`
	Year     time.Time `json:"year"`
}

type GetFileListByYearRow struct {
	Filename   string         `json:"filename"`
	Filesize   int64          `json:"filesize"`
	Originalid sql.NullString `json:"originalid"`
	Inserted   sql.NullTime   `json:"inserted"`
}

func (q *Queries) GetFileListByYear(ctx context.Context, arg GetFileListByYearParams) ([]GetFileListByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getFileListByYear, arg.User, arg.Category, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFileListByYearRow
	for rows.Next() {
		var i GetFileListByYearRow
		if err := rows.Scan(
			&i.Filename,
			&i.Filesize,
			&i.Originalid,
			&i.Inserted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutputMonths = `-- name: GetOutputMonths :many
SELECT DATE_FORMAT(stamp, '%Y-%m') AS m
FROM tFileStore
WHERE user = ? AND YEAR(stamp) = ?
GROUP BY m
`

type GetOutputMonthsParams struct {
	User string    `json:"user"`
	Year time.Time `json:"year"`
}

func (q *Queries) GetOutputMonths(ctx context.Context, arg GetOutputMonthsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getOutputMonths, arg.User, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var m string
		if err := rows.Scan(&m); err != nil {
			return nil, err
		}
		items = append(items, m)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutputYears = `-- name: GetOutputYears :many
SELECT DISTINCT(YEAR(stamp)) AS year, COUNT(YEAR(stamp)) AS c
FROM tFileStore
WHERE user = ?
GROUP BY YEAR(stamp)
`

type GetOutputYearsRow struct {
	Year int32 `json:"year"`
	C    int64 `json:"c"`
}

func (q *Queries) GetOutputYears(ctx context.Context, user string) ([]GetOutputYearsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOutputYears, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutputYearsRow
	for rows.Next() {
		var i GetOutputYearsRow
		if err := rows.Scan(&i.Year, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFileStore = `-- name: InsertFileStore :execresult
INSERT INTO tFileStore (user, stamp, category, filename, payloadId, processorId, content, contentsize)
VALUES (?, ?, ?, ?,
        ?, ?, ?, ?)
`

type InsertFileStoreParams struct {
	User        string         `json:"user"`
	Stamp       time.Time      `json:"stamp"`
	Category    string         `json:"category"`
	Filename    string         `json:"filename"`
	PayloadID   uint64         `json:"payload_id"`
	ProcessorID uint64         `json:"processor_id"`
	Content     sql.NullString `json:"content"`
	Contentsize int64          `json:"contentsize"`
}

func (q *Queries) InsertFileStore(ctx context.Context, arg InsertFileStoreParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertFileStore,
		arg.User,
		arg.Stamp,
		arg.Category,
		arg.Filename,
		arg.PayloadID,
		arg.ProcessorID,
		arg.Content,
		arg.Contentsize,
	)
}
