// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
)

const getEnabledJobs = `-- name: GetEnabledJobs :many
SELECT id, jobschedule, jobclass, jobenabled FROM tJobs WHERE jobEnabled = TRUE
`

func (q *Queries) GetEnabledJobs(ctx context.Context) ([]Tjob, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tjob
	for rows.Next() {
		var i Tjob
		if err := rows.Scan(
			&i.ID,
			&i.Jobschedule,
			&i.Jobclass,
			&i.Jobenabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
