// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyring.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addKeyToKeyring = `-- name: AddKeyToKeyring :execresult
INSERT INTO tKeyring (user, keyname, privatekey, publickey)
VALUES (?, ?, ?, ?)
`

type AddKeyToKeyringParams struct {
	User       string         `json:"user"`
	Keyname    string         `json:"keyname"`
	Privatekey sql.NullString `json:"privatekey"`
	Publickey  sql.NullString `json:"publickey"`
}

func (q *Queries) AddKeyToKeyring(ctx context.Context, arg AddKeyToKeyringParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addKeyToKeyring,
		arg.User,
		arg.Keyname,
		arg.Privatekey,
		arg.Publickey,
	)
}
