// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type Teligibilityjob struct {
	ID           int64          `json:"id"`
	User         string         `json:"user"`
	Inserted     time.Time      `json:"inserted"`
	Processed    sql.NullTime   `json:"processed"`
	Plugin       string         `json:"plugin"`
	Payload      sql.NullString `json:"payload"`
	Response     sql.NullString `json:"response"`
	Resubmission bool           `json:"resubmission"`
	Completed    bool           `json:"completed"`
}

type Tfilestore struct {
	ID          int64          `json:"id"`
	User        string         `json:"user"`
	Stamp       time.Time      `json:"stamp"`
	Category    string         `json:"category"`
	Filename    string         `json:"filename"`
	Payloadid   uint64         `json:"payloadid"`
	Processorid uint64         `json:"processorid"`
	Content     sql.NullString `json:"content"`
	Contentsize int64          `json:"contentsize"`
}

type Tjob struct {
	ID          int64  `json:"id"`
	Jobschedule string `json:"jobschedule"`
	Jobclass    string `json:"jobclass"`
	Jobenabled  bool   `json:"jobenabled"`
}

type Tkeyring struct {
	ID         int64          `json:"id"`
	User       string         `json:"user"`
	Keyname    string         `json:"keyname"`
	Privatekey sql.NullString `json:"privatekey"`
	Publickey  sql.NullString `json:"publickey"`
}

type Tpatch struct {
	ID        int64     `json:"id"`
	Patchname string    `json:"patchname"`
	Stamp     time.Time `json:"stamp"`
}

type Tpayload struct {
	ID              int64          `json:"id"`
	InsertStamp     time.Time      `json:"insert_stamp"`
	User            string         `json:"user"`
	Payload         sql.NullString `json:"payload"`
	Originalid      sql.NullString `json:"originalid"`
	Renderplugin    string         `json:"renderplugin"`
	Renderoption    string         `json:"renderoption"`
	Transportplugin string         `json:"transportplugin"`
	Transportoption sql.NullString `json:"transportoption"`
	Payloadstate    sql.NullString `json:"payloadstate"`
}

type Tplugin struct {
	Plugin       string         `json:"plugin"`
	Version      string         `json:"version"`
	Author       string         `json:"author"`
	Category     string         `json:"category"`
	Inputformat  sql.NullString `json:"inputformat"`
	Outputformat sql.NullString `json:"outputformat"`
}

type Tpluginoption struct {
	Poption      string         `json:"poption"`
	Plugin       string         `json:"plugin"`
	Fullname     string         `json:"fullname"`
	Version      string         `json:"version"`
	Author       string         `json:"author"`
	Category     string         `json:"category"`
	Inputformat  sql.NullString `json:"inputformat"`
	Outputformat sql.NullString `json:"outputformat"`
}

type Tpluginoptiontransform struct {
	Poptionold string `json:"poptionold"`
	Poption    string `json:"poption"`
	Plugin     string `json:"plugin"`
}

type Tprocessor struct {
	ID        int64          `json:"id"`
	Threadid  uint32         `json:"threadid"`
	Payloadid uint64         `json:"payloadid"`
	Stage     sql.NullString `json:"stage"`
	Plugin    string         `json:"plugin"`
	Tsstart   sql.NullTime   `json:"tsstart"`
	Tsend     sql.NullTime   `json:"tsend"`
	Pinput    sql.NullString `json:"pinput"`
	Poutput   sql.NullString `json:"poutput"`
}

type Trole struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Rolename string `json:"rolename"`
}

type Tscooper struct {
	ID           int64          `json:"id"`
	Scooperclass string         `json:"scooperclass"`
	User         string         `json:"user"`
	Stamp        time.Time      `json:"stamp"`
	Host         string         `json:"host"`
	Path         string         `json:"path"`
	Filename     string         `json:"filename"`
	Content      sql.NullString `json:"content"`
}

type Tsshhostkey struct {
	ID       int64          `json:"id"`
	Hostname string         `json:"hostname"`
	Port     uint32         `json:"port"`
	Hostkey  sql.NullString `json:"hostkey"`
}

type Ttranslation struct {
	Plugin       string `json:"plugin"`
	Inputformat  string `json:"inputformat"`
	Outputformat string `json:"outputformat"`
}

type Tuser struct {
	ID                     int64          `json:"id"`
	Username               string         `json:"username"`
	Passhash               string         `json:"passhash"`
	Contactemail           sql.NullString `json:"contactemail"`
	Callbackserviceuri     sql.NullString `json:"callbackserviceuri"`
	Callbackservicewsdluri sql.NullString `json:"callbackservicewsdluri"`
	Callbackusername       sql.NullString `json:"callbackusername"`
	Callbackpassword       sql.NullString `json:"callbackpassword"`
	Role                   sql.NullString `json:"role"`
}

type Tuserconfig struct {
	User       string         `json:"user"`
	Cnamespace string         `json:"cnamespace"`
	Coption    string         `json:"coption"`
	Cvalue     sql.NullString `json:"cvalue"`
}

type Tuserrole struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Rolename string `json:"rolename"`
}
