// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payload.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getPayloadById = `-- name: GetPayloadById :one
SELECT id, insert_stamp, user, payload, originalid, renderplugin, renderoption, transportplugin, transportoption, payloadstate FROM tPayload WHERE id = ?
`

func (q *Queries) GetPayloadById(ctx context.Context, id int64) (Tpayload, error) {
	row := q.db.QueryRowContext(ctx, getPayloadById, id)
	var i Tpayload
	err := row.Scan(
		&i.ID,
		&i.InsertStamp,
		&i.User,
		&i.Payload,
		&i.Originalid,
		&i.Renderplugin,
		&i.Renderoption,
		&i.Transportplugin,
		&i.Transportoption,
		&i.Payloadstate,
	)
	return i, err
}

const insertPayload = `-- name: InsertPayload :execresult
INSERT INTO tPayload (user, payload, renderPlugin, renderOption, transportPlugin, transportOption, originalId)
VALUES (?, ?, ?, ?,
        ?, ?, ?)
`

type InsertPayloadParams struct {
	User            string         `json:"user"`
	Payload         sql.NullString `json:"payload"`
	RenderPlugin    string         `json:"render_plugin"`
	RenderOption    string         `json:"render_option"`
	TransportPlugin string         `json:"transport_plugin"`
	TransportOption sql.NullString `json:"transport_option"`
	OriginalID      sql.NullString `json:"original_id"`
}

func (q *Queries) InsertPayload(ctx context.Context, arg InsertPayloadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPayload,
		arg.User,
		arg.Payload,
		arg.RenderPlugin,
		arg.RenderOption,
		arg.TransportPlugin,
		arg.TransportOption,
		arg.OriginalID,
	)
}

const resubmitPayload = `-- name: ResubmitPayload :execresult
INSERT INTO tPayload (user, payload, renderPlugin, renderOption, transportPlugin, transportOption, originalId)
SELECT tPayload.user, tPayload.payload, tPayload.renderPlugin, tPayload.renderOption, tPayload.transportPlugin, tPayload.transportOption, tPayload.originalId
FROM tPayload WHERE tPayload.id = ? AND tPayload.user = ?
`

type ResubmitPayloadParams struct {
	ID   int64  `json:"id"`
	User string `json:"user"`
}

func (q *Queries) ResubmitPayload(ctx context.Context, arg ResubmitPayloadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resubmitPayload, arg.ID, arg.User)
}
