// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugins.sql

package dbgen

import (
	"context"
)

const getPluginOptions = `-- name: GetPluginOptions :many
SELECT poption, plugin, fullname, version, author, category, inputformat, outputformat FROM tPluginOptions WHERE plugin = ?
`

func (q *Queries) GetPluginOptions(ctx context.Context, plugin string) ([]Tpluginoption, error) {
	rows, err := q.db.QueryContext(ctx, getPluginOptions, plugin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tpluginoption
	for rows.Next() {
		var i Tpluginoption
		if err := rows.Scan(
			&i.Poption,
			&i.Plugin,
			&i.Fullname,
			&i.Version,
			&i.Author,
			&i.Category,
			&i.Inputformat,
			&i.Outputformat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPluginsByCategory = `-- name: GetPluginsByCategory :many
SELECT plugin, version, author, category, inputformat, outputformat FROM tPlugins WHERE category = ?
`

func (q *Queries) GetPluginsByCategory(ctx context.Context, category string) ([]Tplugin, error) {
	rows, err := q.db.QueryContext(ctx, getPluginsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tplugin
	for rows.Next() {
		var i Tplugin
		if err := rows.Scan(
			&i.Plugin,
			&i.Version,
			&i.Author,
			&i.Category,
			&i.Inputformat,
			&i.Outputformat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
