// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package dbgen

import (
	"context"
)

const callStatus = `-- name: CallStatus :one
CALL p_Status(?, ?)
`

type CallStatusParams struct {
	Username  interface{} `json:"username"`
	PayloadID interface{} `json:"payload_id"`
}

type CallStatusRow struct {
}

func (q *Queries) CallStatus(ctx context.Context, arg CallStatusParams) (CallStatusRow, error) {
	row := q.db.QueryRowContext(ctx, callStatus, arg.Username, arg.PayloadID)
	var i CallStatusRow
	err := row.Scan()
	return i, err
}
