// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: translation.sql
//
// HAND-EDITED 2026-09-15: this file is what `sqlc generate` emits for
// internal/db/queries/translation.sql, written out by hand because sqlc is not
// installed in this environment. The single query is the tTranslation lookup
// p_ResolveTranslationPlugin performs (migrations/001_legacy.up.sql:327-338),
// minus the FIND_IN_SET clause that translation.FormatInSet applies in Go.

package dbgen

import (
	"context"
)

const getTranslationsByInputFormat = `-- name: GetTranslationsByInputFormat :many
SELECT plugin, inputformat, outputformat FROM tTranslation WHERE inputformat = ? ORDER BY plugin
`

// GetTranslationsByInputFormat returns every tTranslation row whose
// inputFormat equals the given format - the candidate translators for a render
// plugin that declares that output format. Ordered by plugin so the caller's
// choice among several candidates is deterministic (the Java's procedure used
// an unordered LIMIT 1).
func (q *Queries) GetTranslationsByInputFormat(ctx context.Context, inputformat string) ([]Ttranslation, error) {
	rows, err := q.db.QueryContext(ctx, getTranslationsByInputFormat, inputformat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ttranslation
	for rows.Next() {
		var i Ttranslation
		if err := rows.Scan(
			&i.Plugin,
			&i.Inputformat,
			&i.Outputformat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
