// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :execresult
INSERT INTO tUser (username, passhash, contactemail, callbackserviceuri, callbackservicewsdluri, callbackusername, callbackpassword)
VALUES (?, ?, ?,
        ?, ?,
        ?, ?)
`

type AddUserParams struct {
	Username               string         `json:"username"`
	Passhash               string         `json:"passhash"`
	Contactemail           sql.NullString `json:"contactemail"`
	Callbackserviceuri     sql.NullString `json:"callbackserviceuri"`
	Callbackservicewsdluri sql.NullString `json:"callbackservicewsdluri"`
	Callbackusername       sql.NullString `json:"callbackusername"`
	Callbackpassword       sql.NullString `json:"callbackpassword"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUser,
		arg.Username,
		arg.Passhash,
		arg.Contactemail,
		arg.Callbackserviceuri,
		arg.Callbackservicewsdluri,
		arg.Callbackusername,
		arg.Callbackpassword,
	)
}

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO tRole (username, rolename) VALUES (?, ?)
`

type AddUserRoleParams struct {
	Username string `json:"username"`
	Rolename string `json:"rolename"`
}

// The Java's UserManagement.addUser writes the new user's role here, as a second
// statement after the tUser insert (INSERT INTO tRole (username, rolename)).
func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, addUserRole, arg.Username, arg.Rolename)
	return err
}

const changePassword = `-- name: ChangePassword :exec
UPDATE tUser SET passhash = ? WHERE username = ?
`

type ChangePasswordParams struct {
	Passhash string `json:"passhash"`
	Username string `json:"username"`
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.ExecContext(ctx, changePassword, arg.Passhash, arg.Username)
	return err
}

const checkUserPassword = `-- name: CheckUserPassword :one
SELECT id, username, passhash, contactemail, callbackserviceuri, callbackservicewsdluri, callbackusername, callbackpassword FROM tUser WHERE username = ? AND passhash = ?
`

type CheckUserPasswordParams struct {
	Username string `json:"username"`
	Passhash string `json:"passhash"`
}

func (q *Queries) CheckUserPassword(ctx context.Context, arg CheckUserPasswordParams) (Tuser, error) {
	row := q.db.QueryRowContext(ctx, checkUserPassword, arg.Username, arg.Passhash)
	var i Tuser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Passhash,
		&i.Contactemail,
		&i.Callbackserviceuri,
		&i.Callbackservicewsdluri,
		&i.Callbackusername,
		&i.Callbackpassword,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT r.rolename FROM tRole r
LEFT OUTER JOIN tUser u ON u.username = r.username
WHERE u.id = ?
`

func (q *Queries) GetRoles(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rolename string
		if err := rows.Scan(&rolename); err != nil {
			return nil, err
		}
		items = append(items, rolename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByName = `-- name: GetRolesByName :many
SELECT r.rolename FROM tRole r
WHERE r.username = ?
ORDER BY r.rolename ASC
`

// Roles live in tRole, keyed by username: tUser has no role column (Java
// UserManagement.SQL_GET_USER reads GROUP_CONCAT(r.rolename) from a tRole join;
// this is the same data as a typed list, without GROUP_CONCAT's truncation at
// group_concat_max_len and its NULL result for a user with no roles).
func (q *Queries) GetRolesByName(ctx context.Context, username string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByName, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rolename string
		if err := rows.Scan(&rolename); err != nil {
			return nil, err
		}
		items = append(items, rolename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, passhash, contactemail, callbackserviceuri, callbackservicewsdluri, callbackusername, callbackpassword FROM tUser WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (Tuser, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i Tuser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Passhash,
		&i.Contactemail,
		&i.Callbackserviceuri,
		&i.Callbackservicewsdluri,
		&i.Callbackusername,
		&i.Callbackpassword,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, username, passhash, contactemail, callbackserviceuri, callbackservicewsdluri, callbackusername, callbackpassword FROM tUser WHERE username = ?
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (Tuser, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, username)
	var i Tuser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Passhash,
		&i.Contactemail,
		&i.Callbackserviceuri,
		&i.Callbackservicewsdluri,
		&i.Callbackusername,
		&i.Callbackpassword,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT username FROM tUser ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
